import { createHash, randomUUID } from 'crypto';
import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  HttpException,
  Inject,
  Injectable,
  InternalServerErrorException,
  NotFoundException,
  Scope,
  UnauthorizedException,
} from '@nestjs/common';
import { REQUEST } from '@nestjs/core';
import { ClientProxy } from '@nestjs/microservices';

// eslint-disable-next-line @typescript-eslint/naming-convention
import Redis from 'ioredis';
import { lastValueFrom } from 'rxjs';

import { RedisService } from '@lib/common/enum/app-microservice.enum';
import {
  ICallContext,
  IMicroservicePayload,
  IRpcErrorPayload,
  IRpcErrorResponse,
} from '@lib/common/interfaces';
import { ILogger } from '@lib/common/modules/log/abstracts/logger.abstract';

/**
 * @description
 * Options for controlling cache behavior in sendWithContext
 */
export interface MicroserviceCacheOptions {
  /**
   * Enable/disable caching for this request
   * @default false
   */
  enabled: boolean;

  /**
   * Cache TTL in seconds
   * @default 300 (5 minutes)
   */
  ttl?: number;

  /**
   * Custom cache key prefix (optional)
   * If not provided, uses cmd as prefix
   */
  keyPrefix?: string;
}

/**
 * @description
 * A request-scoped service that provides a standardized wrapper for making microservice calls.
 * It automatically handles call context propagation (for tracing and user identity)
 * and provides structured logging for every request and response.
 */
@Injectable({ scope: Scope.REQUEST })
export class MicroserviceClientService {
  /**
   * @param request Injects the current request object (from an incoming HTTP call)
   * to extract user session and trace headers for context propagation.
   * @param redisClient Injects the Redis client for caching microservice responses
   */
  constructor(
    @Inject(REQUEST) private readonly request: Request,
    @Inject(RedisService.name) private readonly redisClient: Redis,
  ) {}

  /**
   * @description
   * Sends a message to a microservice with an automatically attached call context and structured logging.
   * Implements robust error handling following best practices from error_handling_guide.md.
   *
   * This method NEVER throws exceptions - it always returns a value (result, defaultValue, or null).
   * All errors are logged internally, allowing callers to handle failures gracefully without try-catch.
   *
   * @param logger The correctly configured LogsService instance from the *calling* service.
   * This ensures that logs generated by this method have the correct service name and version.
   *
   * @param client The `ClientProxy` instance for the target microservice (e.g., this.usersService).
   * @param cmd The command pattern for the message (e.g., { cmd: 'findUserById' }).
   * @param payload The data payload to send.
   * @param defaultValue A value to return if the microservice call fails or returns an empty response.
   * If not provided, the method returns `null` on errors.
   * @param cacheOptions Optional caching configuration for the request.
   *
   * @returns A Promise that resolves with:
   * - The successful result from the microservice, OR
   * - The provided defaultValue on error (if defaultValue was provided), OR
   * - `null` on error (if no defaultValue was provided)
   *
   * @example
   * // Without defaultValue - returns null on error
   * const patient = await sendWithContext(logger, client, { cmd: 'get_patient' }, { id });
   * if (!patient) {
   *   throw new NotFoundException('Patient not found');
   * }
   *
   * @example
   * // With defaultValue - returns empty array on error
   * const patients = await sendWithContext(logger, client, { cmd: 'get_patients' }, {}, []);
   * // patients will be [] if service fails
   *
   * @example
   * // With caching enabled
   * const patient = await sendWithContext(
   *   logger,
   *   client,
   *   { cmd: 'get_patient' },
   *   { id: '123' },
   *   null,
   *   { enabled: true, ttl: 600 } // Cache for 10 minutes
   * );
   */
  public async sendWithContext<TResult, TInput>(
    logger: ILogger,
    client: ClientProxy,
    cmd: { cmd: string },
    payload: TInput,
    defaultValue: TResult | null = null,
    cacheOptions?: MicroserviceCacheOptions,
  ): Promise<TResult | null> {
    // Step 1: Build the call context and the trace fields shared by every log line.
    const { context, correlationId, traceFields } = this.buildTraceContext();

    // Step 2: Check cache if enabled
    if (cacheOptions?.enabled === true) {
      const cacheKey = this.generateCacheKey(
        cmd.cmd,
        payload,
        cacheOptions.keyPrefix,
      );

      try {
        const cachedData = await this.redisClient.get(cacheKey);

        if (cachedData !== null) {
          const cachedResult = JSON.parse(cachedData) as TResult;

          logger.info({
            message: `[Cache Hit] Retrieved cached data for command '${cmd.cmd}'`,
            context: {
              action: `CACHE_HIT_${cmd.cmd.toUpperCase()}`,
              correlation_id: correlationId,
              cache_key: cacheKey,
            },
          });

          return cachedResult;
        }

        logger.debug({
          message: `[Cache Miss] No cached data found for command '${cmd.cmd}'`,
          context: {
            action: `CACHE_MISS_${cmd.cmd.toUpperCase()}`,
            correlation_id: correlationId,
            cache_key: cacheKey,
          },
        });
      } catch (cacheError) {
        // Log cache errors but continue with microservice call
        logger.warn({
          message: `[Cache Error] Failed to retrieve cache for command '${cmd.cmd}'`,
          context: {
            action: `CACHE_ERROR_${cmd.cmd.toUpperCase()}`,
            correlation_id: correlationId,
            error:
              cacheError instanceof Error
                ? cacheError.message
                : String(cacheError),
          },
        });
      }
    }

    // Step 3: Assemble the standardized microservice payload, combining the actual
    // data payload with the call context.
    const dataToSend = this.buildMicroservicePayload(payload, context);

    // Step 4: Log the outgoing request for traceability.
    logger.info({
      message: `[Microservice Request] Sending command '${cmd.cmd}'`,
      context: {
        action: `MICROSERVICE_SEND_${cmd.cmd.toUpperCase()}`,
        ...traceFields,
        payload: this.sanitizePayloadForLog(payload),
      },
    });

    const startTime = Date.now();
    try {
      // Step 5: Execute the microservice call and await the response.
      const result = await lastValueFrom(
        client.send<TResult>(cmd, dataToSend),
        {
          defaultValue,
        },
      );
      const duration = Date.now() - startTime;

      // Step 6: Log the successful response.
      logger.info({
        message: `[Microservice Response] Received response for command '${cmd.cmd}'`,
        context: {
          action: `MICROSERVICE_SUCCESS_${cmd.cmd.toUpperCase()}`,
          ...traceFields,
          duration_ms: duration,
          // Avoid logging the full 'result' if it can contain sensitive or large data.
        },
      });

      // Step 7: Cache the result if caching is enabled and result is valid
      if (
        cacheOptions?.enabled === true &&
        result !== null &&
        result !== undefined
      ) {
        const cacheKey = this.generateCacheKey(
          cmd.cmd,
          payload,
          cacheOptions.keyPrefix,
        );
        const ttl = cacheOptions.ttl ?? 300; // Default 5 minutes

        try {
          await this.redisClient.setex(cacheKey, ttl, JSON.stringify(result));

          logger.debug({
            message: `[Cache Set] Cached response for command '${cmd.cmd}'`,
            context: {
              action: `CACHE_SET_${cmd.cmd.toUpperCase()}`,
              correlation_id: correlationId,
              cache_key: cacheKey,
              ttl_seconds: ttl,
            },
          });
        } catch (cacheError) {
          // Log cache errors but don't fail the request
          logger.warn({
            message: `[Cache Error] Failed to cache response for command '${cmd.cmd}'`,
            context: {
              action: `CACHE_SET_ERROR_${cmd.cmd.toUpperCase()}`,
              correlation_id: correlationId,
              error:
                cacheError instanceof Error
                  ? cacheError.message
                  : String(cacheError),
            },
          });
        }
      }

      return result;
    } catch (error) {
      // Step 6: Log the error with full context internally
      const duration = Date.now() - startTime;

      // Debug: Log error type information
      // const errorObj = error as Record<string, unknown>;
      // logger.info({
      //     message: `[Debug] Caught error in microservice call`,
      //     context: {
      //         action: 'ERROR_TYPE_DEBUG',
      //         errorType: typeof error,
      //         isError: error instanceof Error,
      //         isRpcException: error instanceof RpcException,
      //         constructorName: error?.constructor?.name,
      //         hasGetError: typeof error?.getError === 'function',
      //         errorKeys: error && typeof error === 'object' ? Object.keys(error) : [],
      //         isPayloadCheck: this.isRpcErrorPayload(error),
      //         isResponseCheck: this.isRpcErrorResponse(error),
      //         statusValue: errorObj?.status,
      //         messageValue: errorObj?.message,
      //     },
      // });

      // TCP transport deserializes RpcException as plain object, not RpcException instance
      // So we check the structure directly instead of instanceof

      // Check for new standardized RPC error format (IRpcErrorPayload)
      if (this.isRpcErrorPayload(error)) {
        this.handleRpcErrorPayload(
          logger,
          cmd.cmd,
          correlationId,
          duration,
          error,
        );
      }

      // Check for legacy RPC error format (IRpcErrorResponse)
      if (this.isRpcErrorResponse(error)) {
        this.handleRpcError(logger, cmd.cmd, correlationId, duration, error);
      }

      // Type guard to safely access error properties
      const errorMessage =
        error instanceof Error ? error.message : String(error);

      // Determine if connection/timeout error for better logging
      const isServiceUnavailable =
        errorMessage.includes('ECONNREFUSED') ||
        errorMessage.includes('timeout');

      // Log error details internally with structured logging
      if (isServiceUnavailable) {
        logger.error(
          `[Microservice Error] Service unavailable for command '${cmd.cmd}'`,
          error instanceof Error ? error : new Error(errorMessage),
          {
            action: `MICROSERVICE_UNAVAILABLE_${cmd.cmd.toUpperCase()}`,
            ...traceFields,
            duration_ms: duration,
            cmd: cmd.cmd,
            error_message: errorMessage,
          },
        );
      } else {
        logger.error(
          `[Microservice Error] Error for command '${cmd.cmd}'`,
          error instanceof Error ? error : new Error(errorMessage),
          {
            action: `MICROSERVICE_ERROR_${cmd.cmd.toUpperCase()}`,
            ...traceFields,
            duration_ms: duration,
            cmd: cmd.cmd,
            error_message: errorMessage,
          },
        );
      }

      if (error instanceof HttpException) {
        throw error;
      }

      // Return fallback for connection/unavailable errors only
      const fallbackValue =
        defaultValue !== null && defaultValue !== undefined
          ? defaultValue
          : null;

      logger.warn({
        message: `[Microservice Fallback] Returning ${fallbackValue === null ? 'null' : 'default value'} for command '${cmd.cmd}' due to ${isServiceUnavailable ? 'service unavailability' : 'error'}`,
        context: {
          action: `MICROSERVICE_FALLBACK_${cmd.cmd.toUpperCase()}`,
          ...traceFields,
          fallback_type: fallbackValue === null ? 'null' : 'defaultValue',
        },
      });

      return fallbackValue;
    }
  }

  /**
   * @description
   * Emits an event to a microservice (fire-and-forget) with an automatically attached
   * call context and structured logging.
   *
   * Unlike `sendWithContext`, this method uses the event-based `ClientProxy.emit()` channel:
   * there is no response to await and no caching. It is intended for one-way domain events
   * (e.g. "rebuild finance summary") where the caller does not need a result.
   *
   * Like `sendWithContext`, this method NEVER throws — delivery errors are logged internally
   * so producers can fire events without wrapping every call in try-catch.
   *
   * The call context (`_context`) is propagated so the trace_id chain stays intact across the
   * event hop, exactly like the request/response path.
   *
   * @param logger The correctly configured LogsService instance from the *calling* service.
   * @param client The `ClientProxy` instance for the target microservice.
   * @param cmd The event pattern to emit (e.g. { cmd: 'rebuild_finance_summary' }).
   * @param payload The data payload to send with the event.
   *
   * @returns A Promise that resolves once the event has been dispatched (or after an error
   * has been logged). It never rejects.
   *
   * @example
   * await emitWithContext(
   *   logger,
   *   client,
   *   { cmd: 'rebuild_finance_summary' },
   *   { visit_id: visitId, ...snapshot },
   * );
   */
  public async emitWithContext<TInput>(
    logger: ILogger,
    client: ClientProxy,
    cmd: { cmd: string },
    payload: TInput,
  ): Promise<void> {
    // Step 1: Build the call context and the trace fields shared by every log line.
    const { context, traceFields } = this.buildTraceContext();

    // Step 2: Assemble the standardized microservice payload, combining the actual
    // data payload with the call context.
    const dataToSend = this.buildMicroservicePayload(payload, context);

    // Step 3: Log the outgoing event for traceability.
    logger.info({
      message: `[Microservice Emit] Emitting event '${cmd.cmd}'`,
      context: {
        action: `MICROSERVICE_EMIT_${cmd.cmd.toUpperCase()}`,
        ...traceFields,
        payload: this.sanitizePayloadForLog(payload),
      },
    });

    const startTime = Date.now();
    try {
      // Step 4: Dispatch the event and await delivery to the transport.
      await lastValueFrom(client.emit(cmd, dataToSend), {
        defaultValue: undefined,
      });
      const duration = Date.now() - startTime;

      // Step 5: Log successful dispatch.
      logger.info({
        message: `[Microservice Emit] Dispatched event '${cmd.cmd}'`,
        context: {
          action: `MICROSERVICE_EMIT_SUCCESS_${cmd.cmd.toUpperCase()}`,
          ...traceFields,
          duration_ms: duration,
        },
      });
    } catch (error) {
      // Step 6: Log dispatch errors internally — never throw on a fire-and-forget event.
      const duration = Date.now() - startTime;
      const errorMessage =
        error instanceof Error ? error.message : String(error);

      logger.error(
        `[Microservice Emit Error] Failed to emit event '${cmd.cmd}'`,
        error instanceof Error ? error : new Error(errorMessage),
        {
          action: `MICROSERVICE_EMIT_ERROR_${cmd.cmd.toUpperCase()}`,
          ...traceFields,
          duration_ms: duration,
          cmd: cmd.cmd,
          error_message: errorMessage,
        },
      );
    }
  }

  /**
   * @description
   * Builds the call context from the incoming request and derives the trace fields that are
   * attached to every log line, so a single trace_id grep spans all hops.
   * Shared by `sendWithContext` and `emitWithContext`.
   */
  private buildTraceContext(): {
    context: ICallContext;
    correlationId: string | undefined;
    traceFields: {
      correlation_id: string | undefined;
      trace_id: string | undefined;
      span_id: string | undefined;
      parent_span_id: string | undefined;
    };
  } {
    const context = this.createCallContext();
    const correlationId = context.trace.correlation_id;

    return {
      context,
      correlationId,
      traceFields: {
        correlation_id: correlationId,
        trace_id: context.trace.trace_id,
        span_id: context.trace.span_id,
        parent_span_id: context.trace.parent_span_id,
      },
    };
  }

  /**
   * @description
   * Assembles the standardized microservice payload, combining the actual data payload with
   * the call context. Shared by `sendWithContext` and `emitWithContext`.
   */
  private buildMicroservicePayload<TInput>(
    payload: TInput,
    context: ICallContext,
  ): IMicroservicePayload<TInput> {
    return {
      payload,
      _context: context,
    };
  }

  /**
   * @description
   * Produces a log-safe copy of the payload, stripping large binary buffers (e.g. uploaded
   * file contents) so they don't bloat or pollute the logs. Shared by the request and event
   * logging paths.
   */
  private sanitizePayloadForLog<TInput>(payload: TInput): unknown {
    if (payload === null || typeof payload !== 'object') {
      return payload;
    }

    const logPayload = { ...(payload as Record<string, unknown>) };
    const fileProperty = logPayload['file'] as
      Record<string, unknown> | undefined;
    if (
      fileProperty &&
      typeof fileProperty === 'object' &&
      'buffer' in fileProperty
    ) {
      logPayload['file'] = { ...fileProperty, buffer: '<Buffer omitted>' };
    }

    return logPayload;
  }

  /**
   * @description
   * Generates a consistent cache key based on command and payload.
   * Uses a hash of the payload to create a deterministic key.
   *
   * @param cmd The command name (e.g., 'get_patient_by_id')
   * @param payload The request payload
   * @param keyPrefix Optional custom prefix (defaults to cmd)
   * @returns A cache key string
   *
   * @example
   * // Returns: "microservice:get_patient:5f8d0e4e6c1b4e2a3f4d5c6b"
   * generateCacheKey('get_patient', { id: '123' })
   */
  private generateCacheKey<TInput>(
    cmd: string,
    payload: TInput,
    keyPrefix?: string,
  ): string {
    // Normalize the payload to ensure consistent hashing
    const normalizedPayload = this.normalizePayload(payload);

    // Create a hash of the payload
    const payloadHash = createHash('sha256')
      .update(JSON.stringify(normalizedPayload))
      .digest('hex')
      .substring(0, 24); // Use first 24 characters for brevity

    const prefix = keyPrefix ?? cmd.replace(/\./g, ':');

    return `microservice:${prefix}:${payloadHash}`;
  }

  /**
   * @description
   * Normalizes payload by sorting keys and removing undefined values
   * to ensure consistent cache key generation.
   *
   * @param payload The payload to normalize
   * @returns Normalized payload
   */
  private normalizePayload<TInput>(payload: TInput): unknown {
    if (payload === null || payload === undefined) {
      return null;
    }

    if (typeof payload !== 'object') {
      return payload;
    }

    if (Array.isArray(payload)) {
      return payload.map((item) => this.normalizePayload(item));
    }

    // Sort keys and remove undefined values
    const normalized: Record<string, unknown> = {};
    const keys = Object.keys(payload).sort();

    for (const key of keys) {
      const value = (payload as Record<string, unknown>)[key];
      if (value !== undefined) {
        normalized[key] = this.normalizePayload(value);
      }
    }

    return normalized;
  }

  /**
   * @description
   * A private helper method to extract user and trace information from the
   * injected request object.
   * @returns An `ICallContext` object.
   */
  private createCallContext(): ICallContext {
    const requestData = this.request as unknown as Record<string, unknown>;
    const userProperty = requestData['user'] as
      Record<string, unknown> | undefined;
    const userSession = userProperty?.['user_session'] as
      Record<string, unknown> | undefined;
    const headers =
      (this.request?.headers as unknown as Record<
        string,
        string | string[] | undefined
      >) ?? {};

    // In an HTTP entrypoint, trace context lives on the request headers (set by
    // contextMiddleware). In a TCP @MessagePattern handler, REQUEST is the incoming
    // RPC payload `{ payload, _context }` — there are no headers, so we fall back to
    // the inbound _context. This keeps the trace_id chain intact across chained hops.
    const inboundTrace = (requestData['_context'] as ICallContext | undefined)
      ?.trace;

    const asString = (v: string | string[] | undefined): string | undefined =>
      typeof v === 'string' ? v : undefined;

    const correlationId =
      asString(headers['x-correlation-id']) ??
      inboundTrace?.correlation_id ??
      'N/A';
    const traceId =
      asString(headers['x-trace-id']) ?? inboundTrace?.trace_id ?? 'N/A';
    // The caller's span becomes our parent; we mint a fresh span for this outgoing call.
    const parentSpanId =
      asString(headers['x-span-id']) ?? inboundTrace?.span_id;

    const xClientIp = headers['x-client-ip'] ?? 'N/A';
    const xClientUserAgent = headers['x-client-user-agent'] ?? 'N/A';

    return {
      user: {
        id:
          typeof userSession?.['id'] === 'string'
            ? userSession['id']
            : undefined,
        roles: Array.isArray(userSession?.['roles'])
          ? (userSession['roles'] as string[])
          : undefined,
        ip_address: typeof xClientIp === 'string' ? xClientIp : undefined,
        user_agent:
          typeof xClientUserAgent === 'string' ? xClientUserAgent : undefined,
      },
      trace: {
        correlation_id: correlationId,
        trace_id: traceId,
        parent_span_id: parentSpanId,
        span_id: randomUUID(),
      },
    };
  }

  /**
   * @description
   * Checks if the response/error is a new standardized RPC error payload (IRpcErrorPayload).
   * This format is returned by RpcExceptionsFilter.
   */
  private isRpcErrorPayload(value: unknown): value is IRpcErrorPayload {
    if (value === null || value === undefined || typeof value !== 'object') {
      return false;
    }

    const obj = value as Record<string, unknown>;

    // Check for new standardized format: { status: { code, message }, errors: [...], meta: {...} }
    return (
      'status' in obj &&
      typeof obj['status'] === 'object' &&
      obj['status'] !== null &&
      'code' in (obj['status'] as Record<string, unknown>) &&
      'errors' in obj &&
      Array.isArray(obj['errors'])
    );
  }

  /**
   * @description
   * Checks if the response/error is a legacy RPC error response from a microservice.
   * RPC errors typically have status_code/statusCode and message properties.
   */
  private isRpcErrorResponse(value: unknown): value is IRpcErrorResponse {
    if (value === null || value === undefined || typeof value !== 'object') {
      return false;
    }

    const obj = value as Record<string, unknown>;

    // Check for RPC error structure
    const hasStatusCode = 'status_code' in obj || 'statusCode' in obj;
    const hasMessage = 'message' in obj;
    const statusCode = (obj['status_code'] ?? obj['statusCode']) as
      number | undefined;

    // Consider it an error if it has a status code >= 400
    return (
      hasStatusCode &&
      hasMessage &&
      typeof statusCode === 'number' &&
      statusCode >= 400
    );
  }

  /**
   * @description
   * Handles new standardized RPC error payload (IRpcErrorPayload) by logging and throwing
   * appropriate HTTP exceptions. This ensures that business logic errors from microservices
   * are properly propagated to the client with correct HTTP status codes.
   */
  private handleRpcErrorPayload(
    logger: ILogger,
    cmd: string,
    correlationId: string | undefined,
    duration: number,
    error: IRpcErrorPayload,
  ): never {
    const statusCode = error.status.code;
    const message = error.status.message;
    const errorDetails = error.errors;

    // Extract the first error detail for the exception message
    const firstError = errorDetails[0];
    const detailMessage = firstError?.detail ?? message;
    // Preserve domain code from DB layer (e.g. 'UNIQUE_VIOLATION', 'FK_VIOLATION')
    const domainCode =
      typeof firstError?.code === 'number' ||
      typeof firstError?.code === 'string'
        ? firstError.code
        : undefined;
    const exceptionBody =
      domainCode !== undefined
        ? { code: domainCode, message: detailMessage }
        : detailMessage;

    // Log the RPC error.
    // A 404 is an expected business outcome (e.g. "no assessment yet"),
    // so log it at `warn` level to keep error logs reserved for genuine
    // failures — otherwise these routine 404s drown out real errors.
    const logContext = {
      action: `MICROSERVICE_RPC_ERROR_${cmd.toUpperCase()}`,
      correlation_id: correlationId,
      duration_ms: duration,
      cmd: cmd,
      status_code: statusCode,
      error_message: message,
      error_details: errorDetails,
    };

    if (statusCode === 404) {
      logger.warn({
        message: `[Microservice RPC] Not found for command '${cmd}'`,
        context: logContext,
      });
    } else {
      logger.error(
        `[Microservice RPC Error] Business error for command '${cmd}'`,
        new Error(detailMessage),
        logContext,
      );
    }

    // Throw appropriate HTTP exception based on status code
    switch (statusCode) {
      case 400:
        throw new BadRequestException(exceptionBody);
      case 401:
        throw new UnauthorizedException(exceptionBody);
      case 403:
        throw new ForbiddenException(exceptionBody);
      case 404:
        throw new NotFoundException(exceptionBody);
      case 409:
        throw new ConflictException(exceptionBody);
      default:
        if (statusCode >= 400 && statusCode < 500) {
          throw new HttpException(exceptionBody, statusCode);
        }
        throw new InternalServerErrorException(exceptionBody);
    }
  }

  /**
   * @description
   * Handles legacy RPC error responses by logging and throwing appropriate HTTP exceptions.
   * This ensures that business logic errors from microservices are properly propagated
   * to the client with correct HTTP status codes.
   */
  private handleRpcError(
    logger: ILogger,
    cmd: string,
    correlationId: string | undefined,
    duration: number,
    error: IRpcErrorResponse,
  ): never {
    const statusCode = error.status_code ?? 500;
    const message = error.message ?? 'Internal server error';
    const errorDetail = error.error;

    // Log the RPC error. A 404 is an expected business outcome, so log it
    // at `warn` level to keep error logs reserved for genuine failures.
    const logContext = {
      action: `MICROSERVICE_RPC_ERROR_${cmd.toUpperCase()}`,
      correlation_id: correlationId,
      duration_ms: duration,
      cmd: cmd,
      status_code: statusCode,
      error_message: message,
      error_detail: errorDetail,
    };

    if (statusCode === 404) {
      logger.warn({
        message: `[Microservice RPC] Not found for command '${cmd}'`,
        context: logContext,
      });
    } else {
      logger.error(
        `[Microservice RPC Error] Business error for command '${cmd}'`,
        new Error(message),
        logContext,
      );
    }

    // Throw appropriate HTTP exception based on status code
    switch (statusCode) {
      case 400:
        throw new BadRequestException(message);
      case 401:
        throw new UnauthorizedException(message);
      case 403:
        throw new ForbiddenException(message);
      case 404:
        throw new NotFoundException(message);
      default:
        if (statusCode >= 400 && statusCode < 500) {
          throw new HttpException(message, statusCode);
        }
        throw new InternalServerErrorException(message);
    }
  }
}
