import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateDocumentTypesAndRunningNumbers1785301476461 implements MigrationInterface {
    name = 'CreateDocumentTypesAndRunningNumbers1785301476461'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "document_types" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_reason" text, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "code" character varying(50) NOT NULL, "name_th" character varying(255) NOT NULL, "name_en" character varying(255) NOT NULL, "print_template_id" uuid NOT NULL, "has_running_number" boolean NOT NULL DEFAULT false, "running_number_format" character varying(255), "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "uq_document_types_code" UNIQUE ("code"), CONSTRAINT "PK_d467d7eeb7c8ce216e90e8494aa" PRIMARY KEY ("id")); COMMENT ON COLUMN "document_types"."id" IS 'รหัสอ้างอิงหลัก'; COMMENT ON COLUMN "document_types"."created_at" IS 'วันที่สร้าง (system)'; COMMENT ON COLUMN "document_types"."created_by" IS 'ผู้บันทึก'; COMMENT ON COLUMN "document_types"."updated_at" IS 'วันที่แก้ไขล่าสุด'; COMMENT ON COLUMN "document_types"."updated_by" IS 'ผู้แก้ไขล่าสุด'; COMMENT ON COLUMN "document_types"."is_deleted" IS 'สถานะการลบ'; COMMENT ON COLUMN "document_types"."deleted_reason" IS 'เหตุผลที่ลบข้อมูล'; COMMENT ON COLUMN "document_types"."deleted_at" IS 'วันที่ลบ'; COMMENT ON COLUMN "document_types"."deleted_by" IS 'ผู้ลบ'; COMMENT ON COLUMN "document_types"."code" IS 'รหัสประเภทเอกสาร (unique) / Document type code'; COMMENT ON COLUMN "document_types"."name_th" IS 'ชื่อประเภทเอกสาร (ไทย) / Document type name (Thai)'; COMMENT ON COLUMN "document_types"."name_en" IS 'ชื่อประเภทเอกสาร (อังกฤษ) / Document type name (English)'; COMMENT ON COLUMN "document_types"."print_template_id" IS 'อ้างอิง print_templates.id ที่ใช้ render เอกสารประเภทนี้'; COMMENT ON COLUMN "document_types"."has_running_number" IS 'เอกสารประเภทนี้มีเลขที่รันอัตโนมัติหรือไม่ / Whether this document type uses a running number'; COMMENT ON COLUMN "document_types"."running_number_format" IS 'รูปแบบเลขที่เอกสาร ใช้ {YYYY}/{YY}/{MM}/{DD}/{SEQ:n} เช่น INV-{YYYY}{MM}-{SEQ:5} — บังคับเมื่อ has_running_number = true / Running number format pattern'; COMMENT ON COLUMN "document_types"."is_active" IS 'สถานะใช้งาน / Is active'`);
        await queryRunner.query(`CREATE TABLE "document_running_numbers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_by" uuid, "is_deleted" boolean NOT NULL DEFAULT false, "deleted_reason" text, "deleted_at" TIMESTAMP WITH TIME ZONE, "deleted_by" uuid, "document_type_id" uuid NOT NULL, "last_running_number" integer NOT NULL DEFAULT '0', "last_value" character varying(255), "last_issued_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "uq_document_running_numbers_document_type_id" UNIQUE ("document_type_id"), CONSTRAINT "PK_6ab757f283a30de05f080835772" PRIMARY KEY ("id")); COMMENT ON COLUMN "document_running_numbers"."id" IS 'รหัสอ้างอิงหลัก'; COMMENT ON COLUMN "document_running_numbers"."created_at" IS 'วันที่สร้าง (system)'; COMMENT ON COLUMN "document_running_numbers"."created_by" IS 'ผู้บันทึก'; COMMENT ON COLUMN "document_running_numbers"."updated_at" IS 'วันที่แก้ไขล่าสุด'; COMMENT ON COLUMN "document_running_numbers"."updated_by" IS 'ผู้แก้ไขล่าสุด'; COMMENT ON COLUMN "document_running_numbers"."is_deleted" IS 'สถานะการลบ'; COMMENT ON COLUMN "document_running_numbers"."deleted_reason" IS 'เหตุผลที่ลบข้อมูล'; COMMENT ON COLUMN "document_running_numbers"."deleted_at" IS 'วันที่ลบ'; COMMENT ON COLUMN "document_running_numbers"."deleted_by" IS 'ผู้ลบ'; COMMENT ON COLUMN "document_running_numbers"."document_type_id" IS 'อ้างอิง document_types.id (1 แถวต่อ 1 ประเภทเอกสาร)'; COMMENT ON COLUMN "document_running_numbers"."last_running_number" IS 'เลขรันล่าสุดที่ออกไป / Last issued running number (digits only)'; COMMENT ON COLUMN "document_running_numbers"."last_value" IS 'เลขที่เอกสารเต็มล่าสุดที่ออกไป ใช้ตรวจสอบ pattern ตอนออกเลขถัดไป / Last issued full document number'; COMMENT ON COLUMN "document_running_numbers"."last_issued_at" IS 'เวลาที่ออกเลขล่าสุด / When the last number was issued'`);
        await queryRunner.query(`ALTER TABLE "document_types" ADD CONSTRAINT "fk_document_types_print_template_id" FOREIGN KEY ("print_template_id") REFERENCES "print_templates"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document_running_numbers" ADD CONSTRAINT "fk_document_running_numbers_document_type_id" FOREIGN KEY ("document_type_id") REFERENCES "document_types"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "document_running_numbers" DROP CONSTRAINT "fk_document_running_numbers_document_type_id"`);
        await queryRunner.query(`ALTER TABLE "document_types" DROP CONSTRAINT "fk_document_types_print_template_id"`);
        await queryRunner.query(`DROP TABLE "document_running_numbers"`);
        await queryRunner.query(`DROP TABLE "document_types"`);
    }

}
